export type Category =
  | 'Cuadros'
  | 'Sets armables'
  | 'Cajas acrílicas'
  | 'Mini momentos'
  | 'Mini Box'
  | 'Llaveros'
  | 'Minifiguras';

export interface Product {
  id: string;
  name: string;
  kicker: string;
  category: Category;
  detail: string;
  image: string;
  tag?: string;
  group?: string;
  occasion: string[];
  description: string;
  minFigures: number;
  maxFigures: number;
  variants: string[];
  allowsPets?: boolean;
  allowsAccessories?: boolean;
  rule: string;
  isActive?: boolean;
  displayOrder?: number;
  basePrice?: number;
  code?: string;
}

export interface VisualChoice {
  name: Category;
  shortName: string;
  description: string;
  image: string;
  maxFigures: number;
}

export const CATEGORY_SHOWCASE: VisualChoice[] = [
  {
    name: 'Cuadros',
    shortName: 'Cuadros',
    description: 'Tallas S (máx. 3), M (máx. 6) y L (máx. 10). Diseñado con minifiguras, mascotas y fondo a tu elección.',
    image: '/images/cuadro-personalizado.webp',
    maxFigures: 10,
  },
  {
    name: 'Sets armables',
    shortName: 'Sets',
    description: 'Escenas armables por grupos temáticos (1 al 4) y ediciones especiales con minifiguras personalizadas.',
    image: '/catalog-assets/sets/243775c4-7b83-46fe-9189-bcb9c7126e19.png',
    maxFigures: 8,
  },
  {
    name: 'Cajas acrílicas',
    shortName: 'Cajas',
    description: 'Caja sencilla (máx. 1) y doble (máx. 4) protegidas para recordar momentos con fondo y accesorios.',
    image: '/catalog-assets/minibox/df814d06-067e-4b15-b7b5-9731d683f9ff.png',
    maxFigures: 4,
  },
  {
    name: 'Mini momentos',
    shortName: 'Momentos',
    description: 'Escenas compactas: con iluminación cálida integrada, sin luz o piezas micro armables.',
    image: '/catalog-assets/sets/4af8d6ef-79eb-4bb0-8dce-915751a36f31.jpg',
    maxFigures: 6,
  },
  {
    name: 'Mini Box',
    shortName: 'Mini Box',
    description: 'Cajas acrílicas temáticas con mini sets armables de herramientas, fitness y música DJ.',
    image: '/catalog-assets/minibox/462fcdf5-8fe1-48a2-8887-faa841811c09.png',
    maxFigures: 4,
  },
  {
    name: 'Llaveros',
    shortName: 'Llaveros',
    description: 'Llaveros personalizados, futbolistas y personajes icónicos para llevar todos los días.',
    image: '/catalog-assets/minifiguras/06bec1bd-01d5-4a30-8593-f3908d2b64bd.jpg',
    maxFigures: 1,
  },
  {
    name: 'Minifiguras',
    shortName: 'Minifiguras',
    description: 'Figuras individuales e imanes coleccionables con cabello, rostro y outfit según inventario.',
    image: '/images/minifiguras.webp',
    maxFigures: 8,
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "cuadro-personalizado",
    name: "Cuadro personalizado",
    kicker: "Tu historia enmarcada",
    category: "Cuadros",
    detail: "S (20x15), M (27x22) y L (32x23)",
    image: "/images/cuadro-personalizado.webp",
    tag: "1 a 10 figuras",
    group: "Cuadros",
    occasion: ["Pareja", "Familia", "Cumplea\u00f1os", "Aniversario", "Graduaci\u00f3n"],
    description: "Un cuadro dise\u00f1ado alrededor de tu historia. Medidas: S (20 x 15 cm, m\u00e1x. 3 minifiguras), M (27 x 22 cm, m\u00e1x. 6 minifiguras) y L (32 x 23 cm, m\u00e1x. 10 minifiguras). Incluye cuadro, minifiguras tipo brick personalizadas, fondo tem\u00e1tico a elecci\u00f3n y empaque con dise\u00f1o para regalo.",
    minFigures: 1,
    maxFigures: 10,
    variants: ["Talla S (20x15 cm) \u00b7 m\u00e1x. 3", "Talla M (27x22 cm) \u00b7 m\u00e1x. 6", "Talla L (32x23 cm) \u00b7 m\u00e1x. 10"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Capacidad m\u00e1xima con mascotas: S hasta 3, M hasta 6, L hasta 10.",
    isActive: true,
    displayOrder: 1,
    basePrice: 96000,
    code: "CUADRO-PER",
  },
  {
    id: "caja-acrilica-personalizada",
    name: "Caja acr\u00edlica personalizada",
    kicker: "Escenas protegidas para recordar",
    category: "Cajas acr\u00edlicas",
    detail: "Caja Sencilla o Doble \u00b7 m\u00e1x. 4 figuras",
    image: "/catalog-assets/minibox/df814d06-067e-4b15-b7b5-9731d683f9ff.png",
    tag: "Caja acr\u00edlica",
    group: "Caja acr\u00edlica",
    occasion: ["Pareja", "Profesiones", "Cumplea\u00f1os", "Aniversario"],
    description: "Caja acr\u00edlica de exhibici\u00f3n para crear una escena personalizada con fondo tem\u00e1tico, minifiguras y accesorios. Opciones: Caja Sencilla (m\u00e1x. 1 figura y 1 mascota) o Caja Doble (hasta 4 figuras, o figuras con moto). Incluye accesorio de cat\u00e1logo y empaque de regalo.",
    minFigures: 1,
    maxFigures: 4,
    variants: ["Caja Sencilla \u00b7 m\u00e1x. 1", "Caja Doble \u00b7 m\u00e1x. 4", "Caja Doble + Moto"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Caja Sencilla m\u00e1x. 1 figura; Caja Doble hasta 4 figuras o con moto. Fondo personalizado por $8.000 adicionales.",
    isActive: true,
    displayOrder: 2,
    basePrice: 60000,
    code: "CAJA-ACR",
  },
  {
    id: "momento-con-luz",
    name: "Mini Momento con Luz",
    kicker: "Piezas tipo lego con iluminaci\u00f3n",
    category: "Mini momentos",
    detail: "Piezas tipo lego + luz LED",
    image: "/catalog-assets/sets/4af8d6ef-79eb-4bb0-8dce-915751a36f31.jpg",
    tag: "Con Luz",
    group: "Con Luz",
    occasion: ["Pareja", "Aniversario", "Cumplea\u00f1os"],
    description: "Escena decorativa en piezas armables tipo lego con sistema de luz c\u00e1lida integrada. Personalizaci\u00f3n de minifiguras en cabello, rostro y outfit seg\u00fan inventario. Incluye empaque de regalo.",
    minFigures: 1,
    maxFigures: 6,
    variants: ["Con luz (1 minifigura)", "Con luz (2 minifiguras)"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "1 minifigura $184.000, 2 minifiguras $210.000. Minifigura adicional por $26.000.",
    isActive: true,
    displayOrder: 3,
    basePrice: 184000,
    code: "MOM-LUZ",
  },
  {
    id: "momento-sin-luz",
    name: "Mini Momento sin Luz",
    kicker: "Piezas tipo lego decorativo",
    category: "Mini momentos",
    detail: "Piezas tipo lego para exhibici\u00f3n",
    image: "/catalog-assets/sets/c0015487-850f-4e69-ba49-f0f11976840e.jpg",
    tag: "Sin Luz",
    group: "Sin Luz",
    occasion: ["Pareja", "Amigos", "Cumplea\u00f1os"],
    description: "Escena decorativa en piezas armables tipo lego sin luz. Ideal para repisas, escritorios y momentos especiales con figuras personalizadas.",
    minFigures: 1,
    maxFigures: 6,
    variants: ["Sin luz (1 minifigura)", "Sin luz (2 minifiguras)"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "1 minifigura $164.000, 2 minifiguras $190.000. Minifigura adicional por $26.000.",
    isActive: true,
    displayOrder: 4,
    basePrice: 164000,
    code: "MOM-NOLUZ",
  },
  {
    id: "momento-mini-armable",
    name: "Mini Momento Micro Armable",
    kicker: "Piezas mini de alta precisi\u00f3n",
    category: "Mini momentos",
    detail: "Piezas mini armables compactas",
    image: "/catalog-assets/sets/243775c4-7b83-46fe-9189-bcb9c7126e19.png",
    tag: "Mini Armable",
    group: "Mini Armables",
    occasion: ["Pareja", "Cumplea\u00f1os", "Detalle"],
    description: "Set armable en escala micro compacta con minifiguras personalizadas. Un detalle delicado y lleno de significado.",
    minFigures: 1,
    maxFigures: 4,
    variants: ["Mini armables (1 minifigura)", "Mini armables (2 minifiguras)"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "1 minifigura $134.000, 2 minifiguras $160.000. Minifigura adicional por $26.000.",
    isActive: true,
    displayOrder: 5,
    basePrice: 134000,
    code: "MOM-MICRO",
  },
  {
    id: "set-altar-enamorados",
    name: "Altar Enamorados",
    kicker: "Para momentos que unen",
    category: "Sets armables",
    detail: "52 piezas \u00b7 Grupo 1",
    image: "/catalog-assets/sets/915f5476-74ff-468e-92fc-3f73cd75edc5.png",
    tag: "Grupo 1",
    group: "Grupo 1",
    occasion: ["Pareja", "Aniversario"],
    description: "Altar Enamorados es un set armable decorativo (52 piezas \u00b7 Grupo 1) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $158.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 6,
    basePrice: 130000,
    code: "MOC0049",
  },
  {
    id: "set-amor-rodante",
    name: "Amor Rodante",
    kicker: "Un viaje de a dos",
    category: "Sets armables",
    detail: "75 piezas \u00b7 Grupo 2",
    image: "/catalog-assets/sets/520a314b-8ab9-418a-9550-1d013f1794fe.png",
    tag: "Grupo 2",
    group: "Grupo 2",
    occasion: ["Pareja", "Aniversario"],
    description: "Amor Rodante es un set armable decorativo (75 piezas \u00b7 Grupo 2) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 2"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 2: 1 minifigura $140.000, 2 minifiguras $168.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 7,
    basePrice: 140000,
    code: "163273",
  },
  {
    id: "set-arbol-sakura",
    name: "\u00c1rbol Sakura",
    kicker: "Naturaleza y romance",
    category: "Sets armables",
    detail: "70 piezas \u00b7 Grupo 1",
    image: "/catalog-assets/sets/84feb517-4fe2-494f-b7ed-4f8c7910d36d.png",
    tag: "Grupo 1",
    group: "Grupo 1",
    occasion: ["Pareja", "Cumplea\u00f1os"],
    description: "\u00c1rbol Sakura es un set armable decorativo (70 piezas \u00b7 Grupo 1) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $158.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 8,
    basePrice: 130000,
    code: "CN00133-A",
  },
  {
    id: "set-bbq",
    name: "Barbacoa con Amigos",
    kicker: "El parche perfecto",
    category: "Sets armables",
    detail: "54 piezas \u00b7 Grupo 1",
    image: "/catalog-assets/sets/28fb4712-de07-4428-b711-ac1fdc81068a.png",
    tag: "Grupo 1",
    group: "Grupo 1",
    occasion: ["Amigos", "Cumplea\u00f1os"],
    description: "Barbacoa con Amigos es un set armable decorativo (54 piezas \u00b7 Grupo 1) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $158.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 9,
    basePrice: 130000,
    code: "MOC4034",
  },
  {
    id: "set-barberia",
    name: "Barber\u00eda Tradicional",
    kicker: "Estilo y detalle",
    category: "Sets armables",
    detail: "85 piezas \u00b7 Grupo 2",
    image: "/catalog-assets/sets/18f2f123-6c81-4c34-9c59-fb4d7074492d.png",
    tag: "Grupo 2",
    group: "Grupo 2",
    occasion: ["Profesiones", "Cumplea\u00f1os"],
    description: "Barber\u00eda Tradicional es un set armable decorativo (85 piezas \u00b7 Grupo 2) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 2"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 2: 1 minifigura $140.000, 2 minifiguras $168.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 10,
    basePrice: 140000,
    code: "8974-4",
  },
  {
    id: "set-bateria",
    name: "Bater\u00eda",
    kicker: "Para quien vive la m\u00fasica",
    category: "Sets armables",
    detail: "35 piezas \u00b7 Grupo 1",
    image: "/catalog-assets/sets/55596977-1ab7-4b2b-9d96-282363e33081.png",
    tag: "Grupo 1",
    group: "Grupo 1",
    occasion: ["M\u00fasica", "Cumplea\u00f1os"],
    description: "Bater\u00eda es un set armable decorativo (35 piezas \u00b7 Grupo 1) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $158.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 11,
    basePrice: 130000,
    code: "MOC4091",
  },
  {
    id: "set-bbc",
    name: "BBC Cervecer\u00eda",
    kicker: "Celebrando los buenos momentos",
    category: "Sets armables",
    detail: "90 piezas \u00b7 Grupo 2",
    image: "/catalog-assets/sets/332c4438-e7e6-4894-bc15-9624ff417095.png",
    tag: "Grupo 2",
    group: "Grupo 2",
    occasion: ["Amigos", "Cumplea\u00f1os"],
    description: "BBC Cervecer\u00eda es un set armable decorativo (90 piezas \u00b7 Grupo 2) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 2"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 2: 1 minifigura $140.000, 2 minifiguras $168.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 12,
    basePrice: 140000,
    code: "B10-74",
  },
  {
    id: "caja-buena-vibra",
    name: "Buena Vibra",
    kicker: "Caja acr\u00edlica noche y m\u00fasica",
    category: "Mini Box",
    detail: "20 piezas \u00b7 Mini Box",
    image: "/catalog-assets/minibox/f639f9d0-9aa9-4b9a-a278-594ce0a45ed2.png",
    tag: "Mini Box",
    group: "Mini Box",
    occasion: ["Amigos", "Cumplea\u00f1os"],
    description: "Buena Vibra es una escena protegida en caja acr\u00edlica que incluye mini set armable (20 piezas \u00b7 Mini Box) y minifiguras personalizadas. Ideal para regalar y exhibir en escritorios o repisas.",
    minFigures: 1,
    maxFigures: 4,
    variants: ["Caja con mini set"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Incluye caja acr\u00edlica, mini set y minifiguras. El valor se confirma seg\u00fan extras.",
    isActive: true,
    displayOrder: 13,
    basePrice: 70000,
    code: "B21-44-2",
  },
  {
    id: "set-camping",
    name: "Camping Aventura",
    kicker: "Noche de fogata y tienda",
    category: "Sets armables",
    detail: "153 piezas \u00b7 Grupo 4",
    image: "/catalog-assets/sets/49b5d8bf-3c18-4785-adfa-77d4574d13f1.png",
    tag: "Grupo 4",
    group: "Grupo 4",
    occasion: ["Amigos", "Cumplea\u00f1os"],
    description: "Camping Aventura es un set armable decorativo (153 piezas \u00b7 Grupo 4) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 4"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 4: 1 minifigura $165.000, 2 minifiguras $195.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 14,
    basePrice: 165000,
    code: "96697378638",
  },
  {
    id: "set-cancha-basquet",
    name: "Cancha de B\u00e1squet",
    kicker: "Pasi\u00f3n por el juego",
    category: "Sets armables",
    detail: "48 piezas \u00b7 Grupo 1",
    image: "/catalog-assets/sets/afd657cf-eae8-4c5d-88e3-09db8c3f61e8.png",
    tag: "Grupo 1",
    group: "Grupo 1",
    occasion: ["Deportes", "Cumplea\u00f1os"],
    description: "Cancha de B\u00e1squet es un set armable decorativo (48 piezas \u00b7 Grupo 1) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $158.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 15,
    basePrice: 130000,
    code: "MOC4081-A",
  },
  {
    id: "set-futbol",
    name: "Cancha de F\u00fatbol",
    kicker: "Para hinchas de verdad",
    category: "Sets armables",
    detail: "20 piezas \u00b7 Grupo 1",
    image: "/catalog-assets/sets/1a75b290-9657-4c33-915c-76bd83113eb9.png",
    tag: "Grupo 1",
    group: "Grupo 1",
    occasion: ["Deportes", "Cumplea\u00f1os"],
    description: "Cancha de F\u00fatbol es un set armable decorativo (20 piezas \u00b7 Grupo 1) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $158.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 16,
    basePrice: 130000,
    code: "LEA-0001",
  },
  {
    id: "set-cascada-tropical",
    name: "Cascada Tropical",
    kicker: "Para\u00edso en miniatura",
    category: "Sets armables",
    detail: "130 piezas \u00b7 Grupo 3",
    image: "/catalog-assets/sets/b2e82c07-cb1f-4445-be15-74f524d98985.png",
    tag: "Grupo 3",
    group: "Grupo 3",
    occasion: ["Pareja", "Vacaciones"],
    description: "Cascada Tropical es un set armable decorativo (130 piezas \u00b7 Grupo 3) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 3"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 3: 1 minifigura $154.000, 2 minifiguras $184.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 17,
    basePrice: 154000,
    code: "4901131696",
  },
  {
    id: "set-cita-bajo-farol",
    name: "Cita bajo el Farol",
    kicker: "Cita bajo la luz tenue",
    category: "Sets armables",
    detail: "Set armable \u00b7 Set Armable",
    image: "/catalog-assets/sets/c80919b7-55ac-4e2f-a021-fe6ca35ec9b2.jpg",
    tag: "Set Armable",
    group: "Grupo 1",
    occasion: ["Pareja", "Aniversario"],
    description: "Cita bajo el Farol es un set armable decorativo (Set armable \u00b7 Set Armable) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $160.000. Minifigura adicional por $24.000.",
    isActive: false,
    displayOrder: 18,
    basePrice: 130000,
    code: "MOC0017-A",
  },
  {
    id: "set-cafe",
    name: "Cita en el Caf\u00e9",
    kicker: "Un plan inolvidable",
    category: "Sets armables",
    detail: "140 piezas \u00b7 Grupo 3",
    image: "/catalog-assets/sets/243775c4-7b83-46fe-9189-bcb9c7126e19.png",
    tag: "Grupo 3",
    group: "Grupo 3",
    occasion: ["Pareja", "Aniversario"],
    description: "Cita en el Caf\u00e9 es un set armable decorativo (140 piezas \u00b7 Grupo 3) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 3"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 3: 1 minifigura $154.000, 2 minifiguras $184.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 19,
    basePrice: 154000,
    code: "401118404",
  },
  {
    id: "set-hotdog",
    name: "Cita en el Hot Dog",
    kicker: "Un cl\u00e1sico callejero",
    category: "Sets armables",
    detail: "100 piezas \u00b7 Grupo 2",
    image: "/catalog-assets/sets/4158bd8a-a71e-4033-baaa-15fc1bccc947.png",
    tag: "Grupo 2",
    group: "Grupo 2",
    occasion: ["Profesiones", "Cumplea\u00f1os"],
    description: "Cita en el Hot Dog es un set armable decorativo (100 piezas \u00b7 Grupo 2) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 2"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 2: 1 minifigura $140.000, 2 minifiguras $168.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 20,
    basePrice: 140000,
    code: "LEA-0004",
  },
  {
    id: "set-otono",
    name: "Cita en Oto\u00f1o",
    kicker: "Colores de temporada",
    category: "Sets armables",
    detail: "99 piezas \u00b7 Grupo 3",
    image: "/catalog-assets/sets/0012f611-7622-45c5-bc55-fef41e6442dc.png",
    tag: "Grupo 3",
    group: "Grupo 3",
    occasion: ["Pareja", "Aniversario"],
    description: "Cita en Oto\u00f1o es un set armable decorativo (99 piezas \u00b7 Grupo 3) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 3"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 3: 1 minifigura $154.000, 2 minifiguras $184.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 21,
    basePrice: 154000,
    code: "99P-ZZ",
  },
  {
    id: "set-cita-entre-flores",
    name: "Cita entre Flores",
    kicker: "Detalles que florecen",
    category: "Sets armables",
    detail: "120 piezas \u00b7 Grupo 3",
    image: "/catalog-assets/sets/fa4e6831-946a-475c-a866-f86409bf6ed2.png",
    tag: "Grupo 3",
    group: "Grupo 3",
    occasion: ["Pareja", "Aniversario"],
    description: "Cita entre Flores es un set armable decorativo (120 piezas \u00b7 Grupo 3) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 3"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 3: 1 minifigura $154.000, 2 minifiguras $184.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 22,
    basePrice: 154000,
    code: "CFLS002",
  },
  {
    id: "set-columpio",
    name: "Columpio",
    kicker: "Tardes inolvidables",
    category: "Sets armables",
    detail: "65 piezas \u00b7 Grupo 2",
    image: "/catalog-assets/sets/48f15862-6c36-493c-a0e7-b55d1fc54d8d.png",
    tag: "Grupo 2",
    group: "Grupo 2",
    occasion: ["Pareja", "Aniversario"],
    description: "Columpio es un set armable decorativo (65 piezas \u00b7 Grupo 2) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 2"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 2: 1 minifigura $140.000, 2 minifiguras $168.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 23,
    basePrice: 140000,
    code: "MOC4145",
  },
  {
    id: "set-copa-mundial",
    name: "Copa Mundial",
    kicker: "La gloria del f\u00fatbol",
    category: "Sets armables",
    detail: "Set armable \u00b7 Set Armable",
    image: "/catalog-assets/sets/1a75b290-9657-4c33-915c-76bd83113eb9.png",
    tag: "Set Armable",
    group: "Grupo 1",
    occasion: ["Deportes", "Coleccionistas"],
    description: "Copa Mundial es un set armable decorativo (Set armable \u00b7 Set Armable) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $160.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 24,
    basePrice: 130000,
    code: "K96280",
  },
  {
    id: "set-corazon-latente",
    name: "Coraz\u00f3n Latente",
    kicker: "El coraz\u00f3n se mueve (late)",
    category: "Sets armables",
    detail: "105 piezas \u00b7 Grupo 4",
    image: "/catalog-assets/sets/4af8d6ef-79eb-4bb0-8dce-915751a36f31.jpg",
    tag: "Grupo 4",
    group: "Grupo 4",
    occasion: ["Pareja", "Aniversario"],
    description: "Coraz\u00f3n Latente es un set armable decorativo (105 piezas \u00b7 Grupo 4) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 4"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 4: 1 minifigura $165.000, 2 minifiguras $195.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 25,
    basePrice: 165000,
    code: "MOC169562",
  },
  {
    id: "set-escapada-natural",
    name: "Escapada Natural",
    kicker: "Desconexi\u00f3n total",
    category: "Sets armables",
    detail: "185 piezas \u00b7 Grupo 4",
    image: "/catalog-assets/sets/c0015487-850f-4e69-ba49-f0f11976840e.jpg",
    tag: "Grupo 4",
    group: "Grupo 4",
    occasion: ["Pareja", "Amigos"],
    description: "Escapada Natural es un set armable decorativo (185 piezas \u00b7 Grupo 4) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 4"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 4: 1 minifigura $165.000, 2 minifiguras $195.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 26,
    basePrice: 165000,
    code: "LEA-0006",
  },
  {
    id: "set-escritorio-gamer",
    name: "Escritorio Gamer",
    kicker: "El setup ideal",
    category: "Sets armables",
    detail: "85 piezas \u00b7 Grupo 1",
    image: "/catalog-assets/sets/e1fee930-56e5-4d80-94e0-7127321c2974.png",
    tag: "Grupo 1",
    group: "Grupo 1",
    occasion: ["Profesiones", "Cumplea\u00f1os"],
    description: "Escritorio Gamer es un set armable decorativo (85 piezas \u00b7 Grupo 1) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $158.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 27,
    basePrice: 130000,
    code: "353682",
  },
  {
    id: "caja-fitness",
    name: "Mini Fitness",
    kicker: "Caja acr\u00edlica de entrenamiento",
    category: "Mini Box",
    detail: "21 piezas \u00b7 Mini Box",
    image: "/catalog-assets/minibox/462fcdf5-8fe1-48a2-8887-faa841811c09.png",
    tag: "Mini Box",
    group: "Mini Box",
    occasion: ["Deportes", "Cumplea\u00f1os"],
    description: "Mini Fitness es una escena protegida en caja acr\u00edlica que incluye mini set armable (21 piezas \u00b7 Mini Box) y minifiguras personalizadas. Ideal para regalar y exhibir en escritorios o repisas.",
    minFigures: 1,
    maxFigures: 4,
    variants: ["Caja con mini set"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Incluye caja acr\u00edlica, mini set y minifiguras. El valor se confirma seg\u00fan extras.",
    isActive: true,
    displayOrder: 28,
    basePrice: 70000,
    code: "366726",
  },
  {
    id: "set-fogata-recuerdos",
    name: "Fogata de Recuerdos",
    kicker: "Bajo las estrellas",
    category: "Sets armables",
    detail: "45 piezas \u00b7 Grupo 1",
    image: "/catalog-assets/sets/c72527d6-26c5-403d-8365-5ad6e2bd4d80.png",
    tag: "Grupo 1",
    group: "Grupo 1",
    occasion: ["Amigos", "Pareja"],
    description: "Fogata de Recuerdos es un set armable decorativo (45 piezas \u00b7 Grupo 1) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $158.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 29,
    basePrice: 130000,
    code: "LEA-0002",
  },
  {
    id: "set-jardin",
    name: "Jard\u00edn Secreto",
    kicker: "Naturaleza en miniatura",
    category: "Sets armables",
    detail: "117 piezas \u00b7 Grupo 2",
    image: "/catalog-assets/sets/48499fd1-79fc-4291-ad14-776a32ed285b.png",
    tag: "Grupo 2",
    group: "Grupo 2",
    occasion: ["Pareja", "Aniversario"],
    description: "Jard\u00edn Secreto es un set armable decorativo (117 piezas \u00b7 Grupo 2) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 2"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 2: 1 minifigura $140.000, 2 minifiguras $168.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 30,
    basePrice: 140000,
    code: "52706390907",
  },
  {
    id: "set-lovers-bridge",
    name: "Lover's Bridge",
    kicker: "Uniendo historias",
    category: "Sets armables",
    detail: "Set armable \u00b7 Set Armable",
    image: "/catalog-assets/sets/a7673a75-6512-47dd-8dcd-0ec55ad872ed.png",
    tag: "Set Armable",
    group: "Grupo 1",
    occasion: ["Pareja", "Aniversario"],
    description: "Lover's Bridge es un set armable decorativo (Set armable \u00b7 Set Armable) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $160.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 31,
    basePrice: 130000,
    code: "LEA-0003",
  },
  {
    id: "set-parque",
    name: "Mini Parque",
    kicker: "Un rinc\u00f3n para dos",
    category: "Sets armables",
    detail: "60 piezas \u00b7 Grupo 1",
    image: "/catalog-assets/sets/0ea7c0ee-26b7-4829-a278-1f271e68a988.png",
    tag: "Grupo 1",
    group: "Grupo 1",
    occasion: ["Pareja", "Aniversario"],
    description: "Mini Parque es un set armable decorativo (60 piezas \u00b7 Grupo 1) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $158.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 32,
    basePrice: 130000,
    code: "MPA001",
  },
  {
    id: "set-billar",
    name: "Mini Billar",
    kicker: "Para el sal\u00f3n de juegos",
    category: "Sets armables",
    detail: "72 piezas \u00b7 Grupo 1",
    image: "/catalog-assets/sets/7bbb7996-777e-4368-8997-b600e6455116.png",
    tag: "Grupo 1",
    group: "Grupo 1",
    occasion: ["Amigos", "Cumplea\u00f1os"],
    description: "Mini Billar es un set armable decorativo (72 piezas \u00b7 Grupo 1) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $158.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 33,
    basePrice: 130000,
    code: "62349712",
  },
  {
    id: "set-modo-aventura",
    name: "Modo Aventura",
    kicker: "Listos para explorar",
    category: "Sets armables",
    detail: "95 piezas \u00b7 Grupo 2",
    image: "/catalog-assets/sets/84e1b978-41e4-4775-a1cf-f098dbeacb7c.png",
    tag: "Grupo 2",
    group: "Grupo 2",
    occasion: ["Amigos", "Cumplea\u00f1os"],
    description: "Modo Aventura es un set armable decorativo (95 piezas \u00b7 Grupo 2) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 2"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 2: 1 minifigura $140.000, 2 minifiguras $168.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 34,
    basePrice: 140000,
    code: "163257",
  },
  {
    id: "set-modo-velocidad",
    name: "Modo Velocidad",
    kicker: "Pura adrenalina",
    category: "Sets armables",
    detail: "68 piezas \u00b7 Grupo 1",
    image: "/catalog-assets/sets/ea4a113e-31c7-458d-921a-786a06bb88a2.png",
    tag: "Grupo 1",
    group: "Grupo 1",
    occasion: ["Deportes", "Cumplea\u00f1os"],
    description: "Modo Velocidad es un set armable decorativo (68 piezas \u00b7 Grupo 1) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $158.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 35,
    basePrice: 130000,
    code: "316200",
  },
  {
    id: "set-motocicleta",
    name: "Motocicleta Cl\u00e1sica",
    kicker: "Aventura sobre dos ruedas",
    category: "Sets armables",
    detail: "Set armable \u00b7 Set Armable",
    image: "/catalog-assets/sets/ea4a113e-31c7-458d-921a-786a06bb88a2.png",
    tag: "Set Armable",
    group: "Grupo 1",
    occasion: ["Deportes", "Coleccionistas"],
    description: "Motocicleta Cl\u00e1sica es un set armable decorativo (Set armable \u00b7 Set Armable) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $160.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 36,
    basePrice: 130000,
    code: "MOC-103498",
  },
  {
    id: "set-navegando-juntos",
    name: "Navegando Juntos",
    kicker: "Rumbo a nuevas aventuras",
    category: "Sets armables",
    detail: "58 piezas \u00b7 Grupo 1",
    image: "/catalog-assets/sets/96e3c92c-8c15-4b7b-ada3-fdfc4b88c2cd.png",
    tag: "Grupo 1",
    group: "Grupo 1",
    occasion: ["Pareja", "Aniversario"],
    description: "Navegando Juntos es un set armable decorativo (58 piezas \u00b7 Grupo 1) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $158.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 37,
    basePrice: 130000,
    code: "886993675",
  },
  {
    id: "set-parque-novios",
    name: "Parque de los Novios",
    kicker: "Paseo al atardecer",
    category: "Sets armables",
    detail: "110 piezas \u00b7 Grupo 3",
    image: "/catalog-assets/sets/a7673a75-6512-47dd-8dcd-0ec55ad872ed.png",
    tag: "Grupo 3",
    group: "Grupo 3",
    occasion: ["Pareja", "Aniversario"],
    description: "Parque de los Novios es un set armable decorativo (110 piezas \u00b7 Grupo 3) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 3"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 3: 1 minifigura $154.000, 2 minifiguras $184.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 38,
    basePrice: 154000,
    code: "7788953028",
  },
  {
    id: "set-parque-diversiones",
    name: "Parque de Diversiones",
    kicker: "Diversi\u00f3n sin l\u00edmites",
    category: "Sets armables",
    detail: "75 piezas \u00b7 Grupo 1",
    image: "/catalog-assets/sets/3f210ffd-191a-43b4-90ae-3c160d917346.png",
    tag: "Grupo 1",
    group: "Grupo 1",
    occasion: ["Familia", "Cumplea\u00f1os"],
    description: "Parque de Diversiones es un set armable decorativo (75 piezas \u00b7 Grupo 1) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $158.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 39,
    basePrice: 130000,
    code: "214030",
  },
  {
    id: "set-piano",
    name: "Piano de Cola",
    kicker: "M\u00fasica en cada nota",
    category: "Sets armables",
    detail: "62 piezas \u00b7 Grupo 2",
    image: "/catalog-assets/sets/c0a1d640-6a3b-468d-8ac2-65b074e1e2aa.png",
    tag: "Grupo 2",
    group: "Grupo 2",
    occasion: ["M\u00fasica", "Cumplea\u00f1os"],
    description: "Piano de Cola es un set armable decorativo (62 piezas \u00b7 Grupo 2) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 2"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 2: 1 minifigura $140.000, 2 minifiguras $168.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 40,
    basePrice: 140000,
    code: "MOC0009",
  },
  {
    id: "set-piscina",
    name: "Pisciencanto",
    kicker: "Vacaciones en miniatura",
    category: "Sets armables",
    detail: "125 piezas \u00b7 Grupo 3",
    image: "/catalog-assets/sets/7ee002c8-dcd0-452b-afb3-c023d94cc4e6.png",
    tag: "Grupo 3",
    group: "Grupo 3",
    occasion: ["Pareja", "Vacaciones"],
    description: "Pisciencanto es un set armable decorativo (125 piezas \u00b7 Grupo 3) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 3"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 3: 1 minifigura $154.000, 2 minifiguras $184.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 41,
    basePrice: 154000,
    code: "6704132905",
  },
  {
    id: "set-rayo-azul",
    name: "Rayo Azul",
    kicker: "Velocidad y estilo",
    category: "Sets armables",
    detail: "65 piezas \u00b7 Grupo 1",
    image: "/catalog-assets/sets/1dd35a46-3c22-49ca-8b29-0b3598fc4ab9.png",
    tag: "Grupo 1",
    group: "Grupo 1",
    occasion: ["Deportes", "Cumplea\u00f1os"],
    description: "Rayo Azul es un set armable decorativo (65 piezas \u00b7 Grupo 1) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $158.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 42,
    basePrice: 130000,
    code: "91401",
  },
  {
    id: "set-rayo-blanco",
    name: "Rayo Blanco",
    kicker: "Dise\u00f1o impecable",
    category: "Sets armables",
    detail: "71 piezas \u00b7 Grupo 1",
    image: "/catalog-assets/sets/46ad66c4-1926-4dbf-b79c-6577283e2596.png",
    tag: "Grupo 1",
    group: "Grupo 1",
    occasion: ["Deportes", "Cumplea\u00f1os"],
    description: "Rayo Blanco es un set armable decorativo (71 piezas \u00b7 Grupo 1) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $158.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 43,
    basePrice: 130000,
    code: "91402",
  },
  {
    id: "set-rayo-rojo",
    name: "Rayo Rojo",
    kicker: "Fuerza y potencia",
    category: "Sets armables",
    detail: "69 piezas \u00b7 Grupo 1",
    image: "/catalog-assets/sets/39883bba-ec0b-4a97-b51d-a867041ed255.png",
    tag: "Grupo 1",
    group: "Grupo 1",
    occasion: ["Deportes", "Cumplea\u00f1os"],
    description: "Rayo Rojo es un set armable decorativo (69 piezas \u00b7 Grupo 1) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $158.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 44,
    basePrice: 130000,
    code: "91404",
  },
  {
    id: "set-rincon-lago",
    name: "Rinc\u00f3n del Lago",
    kicker: "Paz y contemplaci\u00f3n",
    category: "Sets armables",
    detail: "248 piezas \u00b7 Grupo 4",
    image: "/catalog-assets/sets/c0015487-850f-4e69-ba49-f0f11976840e.jpg",
    tag: "Grupo 4",
    group: "Grupo 4",
    occasion: ["Pareja", "Amigos"],
    description: "Rinc\u00f3n del Lago es un set armable decorativo (248 piezas \u00b7 Grupo 4) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 4"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 4: 1 minifigura $165.000, 2 minifiguras $195.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 45,
    basePrice: 165000,
    code: "5503286775",
  },
  {
    id: "set-sala-juntas",
    name: "Sala de Juntas",
    kicker: "Grandes decisiones",
    category: "Sets armables",
    detail: "88 piezas \u00b7 Grupo 3",
    image: "/catalog-assets/sets/cf62cf7f-4368-4195-a69d-ffbca41f12cd.png",
    tag: "Grupo 3",
    group: "Grupo 3",
    occasion: ["Profesiones", "Graduaci\u00f3n"],
    description: "Sala de Juntas es un set armable decorativo (88 piezas \u00b7 Grupo 3) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 3"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 3: 1 minifigura $154.000, 2 minifiguras $184.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 46,
    basePrice: 154000,
    code: "MOC4085",
  },
  {
    id: "set-sala-premium",
    name: "Sala Premium",
    kicker: "Espacios de distinci\u00f3n",
    category: "Sets armables",
    detail: "95 piezas \u00b7 Grupo 3",
    image: "/catalog-assets/sets/9555fbdb-be08-4e14-a3f2-646b37d924fb.png",
    tag: "Grupo 3",
    group: "Grupo 3",
    occasion: ["Profesiones", "Graduaci\u00f3n"],
    description: "Sala Premium es un set armable decorativo (95 piezas \u00b7 Grupo 3) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 3"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 3: 1 minifigura $154.000, 2 minifiguras $184.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 47,
    basePrice: 154000,
    code: "1568056459",
  },
  {
    id: "set-salita-familiar",
    name: "Salita Familiar",
    kicker: "El calor del hogar",
    category: "Sets armables",
    detail: "78 piezas \u00b7 Grupo 2",
    image: "/catalog-assets/sets/b9c3ab23-f237-4574-a4f7-5ef529361cb8.png",
    tag: "Grupo 2",
    group: "Grupo 2",
    occasion: ["Familia", "Cumplea\u00f1os"],
    description: "Salita Familiar es un set armable decorativo (78 piezas \u00b7 Grupo 2) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 2"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 2: 1 minifigura $140.000, 2 minifiguras $168.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 48,
    basePrice: 140000,
    code: "MOC0021-P",
  },
  {
    id: "set-semillas-amor",
    name: "Semillas de Amor",
    kicker: "Cultivando recuerdos",
    category: "Sets armables",
    detail: "82 piezas \u00b7 Grupo 2",
    image: "/catalog-assets/sets/f542f8e5-57a3-447a-8700-cb747558f0be.png",
    tag: "Grupo 2",
    group: "Grupo 2",
    occasion: ["Pareja", "Aniversario"],
    description: "Semillas de Amor es un set armable decorativo (82 piezas \u00b7 Grupo 2) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 2"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 2: 1 minifigura $140.000, 2 minifiguras $168.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 49,
    basePrice: 140000,
    code: "T18741",
  },
  {
    id: "set-astronauta",
    name: "Set Astronauta",
    kicker: "Una aventura espacial",
    category: "Sets armables",
    detail: "152 piezas \u00b7 Grupo 3",
    image: "/catalog-assets/sets/6fdb0ac4-426f-4e27-bac0-6ddaf70a4bd2.png",
    tag: "Grupo 3",
    group: "Grupo 3",
    occasion: ["Profesiones", "Graduaci\u00f3n"],
    description: "Set Astronauta es un set armable decorativo (152 piezas \u00b7 Grupo 3) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 3"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 3: 1 minifigura $154.000, 2 minifiguras $184.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 50,
    basePrice: 154000,
    code: "89644",
  },
  {
    id: "set-casita-up",
    name: "Set Casita UP",
    kicker: "Mecanismo de elevaci\u00f3n",
    category: "Sets armables",
    detail: "686 piezas \u00b7 Especial 686 pzs",
    image: "/catalog-assets/sets/4af8d6ef-79eb-4bb0-8dce-915751a36f31.jpg",
    tag: "Especial 686 pzs",
    group: "Edici\u00f3n Especial Casita UP",
    occasion: ["Pareja", "Familia", "Aniversario"],
    description: "Set de 686 piezas inspirado en la Casita UP. Cuenta con un mecanismo especial para mantenerse elevada o apoyada en el piso. Incluye minifiguras personalizadas, caja personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Edici\u00f3n Especial Casita UP"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "1 minifigura $273.000, 2 minifiguras $295.000. Minifiguras adicionales por $24.000.",
    isActive: true,
    displayOrder: 51,
    basePrice: 273000,
    code: "DK7025",
  },
  {
    id: "set-cocina",
    name: "Set Cocina",
    kicker: "El coraz\u00f3n del hogar",
    category: "Sets armables",
    detail: "135 piezas \u00b7 Grupo 3",
    image: "/catalog-assets/sets/8d92d88a-5ef5-4abd-aa8d-d466d3460ec0.png",
    tag: "Grupo 3",
    group: "Grupo 3",
    occasion: ["Familia", "Cumplea\u00f1os"],
    description: "Set Cocina es un set armable decorativo (135 piezas \u00b7 Grupo 3) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 3"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 3: 1 minifigura $154.000, 2 minifiguras $184.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 52,
    basePrice: 154000,
    code: "89698",
  },
  {
    id: "set-consultorio",
    name: "Set Consultorio",
    kicker: "Celebra su vocaci\u00f3n m\u00e9dica",
    category: "Sets armables",
    detail: "158 piezas \u00b7 Grupo 3",
    image: "/catalog-assets/sets/21c21329-083f-488c-8674-b193e95c1f2a.png",
    tag: "Grupo 3",
    group: "Grupo 3",
    occasion: ["Profesiones", "Graduaci\u00f3n"],
    description: "Set Consultorio es un set armable decorativo (158 piezas \u00b7 Grupo 3) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 3"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 3: 1 minifigura $154.000, 2 minifiguras $184.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 53,
    basePrice: 154000,
    code: "89695",
  },
  {
    id: "set-dentista",
    name: "Set Dentista",
    kicker: "Sonrisas perfectas",
    category: "Sets armables",
    detail: "145 piezas \u00b7 Grupo 3",
    image: "/catalog-assets/sets/d61b635d-0599-4f0c-8050-bf935bf97428.png",
    tag: "Grupo 3",
    group: "Grupo 3",
    occasion: ["Profesiones", "Graduaci\u00f3n"],
    description: "Set Dentista es un set armable decorativo (145 piezas \u00b7 Grupo 3) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 3"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 3: 1 minifigura $154.000, 2 minifiguras $184.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 54,
    basePrice: 154000,
    code: "D610001",
  },
  {
    id: "set-estudio-arte",
    name: "Set Estudio de Arte",
    kicker: "Creatividad al m\u00e1ximo",
    category: "Sets armables",
    detail: "128 piezas \u00b7 Grupo 3",
    image: "/catalog-assets/sets/34cc4235-9592-40ff-8ef2-0b470504ca8e.png",
    tag: "Grupo 3",
    group: "Grupo 3",
    occasion: ["Profesiones", "Graduaci\u00f3n"],
    description: "Set Estudio de Arte es un set armable decorativo (128 piezas \u00b7 Grupo 3) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 3"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 3: 1 minifigura $154.000, 2 minifiguras $184.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 55,
    basePrice: 154000,
    code: "89691",
  },
  {
    id: "set-foto",
    name: "Set Fotograf\u00eda",
    kicker: "Para quienes capturan momentos",
    category: "Sets armables",
    detail: "167 piezas \u00b7 Grupo 3",
    image: "/catalog-assets/sets/003c24d6-8918-4aec-8583-c4f59a045131.png",
    tag: "Grupo 3",
    group: "Grupo 3",
    occasion: ["Profesiones", "Graduaci\u00f3n"],
    description: "Set Fotograf\u00eda es un set armable decorativo (167 piezas \u00b7 Grupo 3) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 3"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 3: 1 minifigura $154.000, 2 minifiguras $184.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 56,
    basePrice: 154000,
    code: "89697",
  },
  {
    id: "set-lab",
    name: "Set Laboratorio",
    kicker: "Para mentes curiosas",
    category: "Sets armables",
    detail: "166 piezas \u00b7 Grupo 3",
    image: "/catalog-assets/sets/28c7a5b5-6118-4db4-a29c-1fd288c86351.png",
    tag: "Grupo 3",
    group: "Grupo 3",
    occasion: ["Profesiones", "Graduaci\u00f3n"],
    description: "Set Laboratorio es un set armable decorativo (166 piezas \u00b7 Grupo 3) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 3"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 3: 1 minifigura $154.000, 2 minifiguras $184.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 57,
    basePrice: 154000,
    code: "89696",
  },
  {
    id: "set-mini-carreras",
    name: "Set Mini Carreras",
    kicker: "Pasi\u00f3n por los motores",
    category: "Sets armables",
    detail: "112 piezas \u00b7 Grupo 3",
    image: "/catalog-assets/sets/10d4848f-a100-4327-8016-1524d33919d3.png",
    tag: "Grupo 3",
    group: "Grupo 3",
    occasion: ["Deportes", "Cumplea\u00f1os"],
    description: "Set Mini Carreras es un set armable decorativo (112 piezas \u00b7 Grupo 3) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 3"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 3: 1 minifigura $154.000, 2 minifiguras $184.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 58,
    basePrice: 154000,
    code: "89692",
  },
  {
    id: "set-musico",
    name: "Set M\u00fasico",
    kicker: "Pasi\u00f3n en el escenario",
    category: "Sets armables",
    detail: "120 piezas \u00b7 Grupo 3",
    image: "/catalog-assets/sets/53a912a7-d25e-4281-b2e1-f95cadbccf38.png",
    tag: "Grupo 3",
    group: "Grupo 3",
    occasion: ["M\u00fasica", "Cumplea\u00f1os"],
    description: "Set M\u00fasico es un set armable decorativo (120 piezas \u00b7 Grupo 3) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 3"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 3: 1 minifigura $154.000, 2 minifiguras $184.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 59,
    basePrice: 154000,
    code: "89693",
  },
  {
    id: "set-skyline",
    name: "Skyline de Ciudades",
    kicker: "New York, Par\u00eds, Londres, Roma",
    category: "Sets armables",
    detail: "598 piezas \u00b7 Skyline",
    image: "/catalog-assets/sets/4c0e83a7-4e34-4bfa-82ec-d0f8f3b15c39.jpg",
    tag: "Skyline",
    group: "Skyline",
    occasion: ["Pareja", "Familia", "Graduaci\u00f3n"],
    description: "Los Skylines representan lugares emblem\u00e1ticos de ciudades del mundo (New York 598 pzs, Par\u00eds 649 pzs, Londres 468 pzs, Roma 373 pzs). Un viaje para no olvidar con minifiguras personalizadas.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["New York", "Par\u00eds", "Londres", "Roma"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "1 minifigura $165.000, 2 minifiguras $195.000. Minifiguras adicionales por $24.000.",
    isActive: true,
    displayOrder: 60,
    basePrice: 165000,
    code: "LEA-0005",
  },
  {
    id: "caja-taller",
    name: "Taller de Pap\u00e1",
    kicker: "Caja acr\u00edlica con mini set",
    category: "Mini Box",
    detail: "65 piezas \u00b7 Mini Box",
    image: "/catalog-assets/minibox/df814d06-067e-4b15-b7b5-9731d683f9ff.png",
    tag: "Mini Box",
    group: "Mini Box",
    occasion: ["Profesiones", "Familia", "Cumplea\u00f1os"],
    description: "Taller de Pap\u00e1 es una escena protegida en caja acr\u00edlica que incluye mini set armable (65 piezas \u00b7 Mini Box) y minifiguras personalizadas. Ideal para regalar y exhibir en escritorios o repisas.",
    minFigures: 1,
    maxFigures: 4,
    variants: ["Caja con mini set"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Incluye caja acr\u00edlica, mini set y minifiguras. El valor se confirma seg\u00fan extras.",
    isActive: true,
    displayOrder: 61,
    basePrice: 70000,
    code: "FRE-232806",
  },
  {
    id: "set-vaiven-amor",
    name: "Vaiv\u00e9n del Amor",
    kicker: "El sube y baja se mueve",
    category: "Sets armables",
    detail: "105 piezas \u00b7 Grupo 4",
    image: "/catalog-assets/sets/4af8d6ef-79eb-4bb0-8dce-915751a36f31.jpg",
    tag: "Grupo 4",
    group: "Grupo 4",
    occasion: ["Pareja", "Aniversario"],
    description: "Vaiv\u00e9n del Amor es un set armable decorativo (105 piezas \u00b7 Grupo 4) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 4"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 4: 1 minifigura $165.000, 2 minifiguras $195.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 62,
    basePrice: 165000,
    code: "MOC4098",
  },
  {
    id: "set-workspace",
    name: "Workspace Oficina",
    kicker: "Tu espacio de inspiraci\u00f3n",
    category: "Sets armables",
    detail: "80 piezas \u00b7 Grupo 1",
    image: "/catalog-assets/sets/3fa135ed-b2e9-47fa-a0c7-6fee7b38394d.png",
    tag: "Grupo 1",
    group: "Grupo 1",
    occasion: ["Profesiones", "Graduaci\u00f3n"],
    description: "Workspace Oficina es un set armable decorativo (80 piezas \u00b7 Grupo 1) tipo brick. Incluye set para armar, minifigura(s) personalizada(s) (cabello, rostro y outfit seg\u00fan inventario), base de exhibici\u00f3n, instrucciones, caja tipo LEGO personalizada y empaque especial.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $158.000. Minifigura adicional por $24.000.",
    isActive: true,
    displayOrder: 63,
    basePrice: 130000,
    code: "MOC0030-A",
  },
  {
    id: "llavero-personalizado",
    name: "Llavero personalizado",
    kicker: "Un personaje para llevar",
    category: "Llaveros",
    detail: "Una minifigura personalizada",
    image: "/catalog-assets/minifiguras/06bec1bd-01d5-4a30-8593-f3908d2b64bd.jpg",
    tag: "Llavero",
    group: "Llaveros",
    occasion: ["Pareja", "Amigos", "Cumplea\u00f1os"],
    description: "Llavero con minifigura personalizada (cabello, rostro, outfit y accesorio seg\u00fan inventario disponible). Un detalle pr\u00e1ctico y significativo para llevar todos los d\u00edas.",
    minFigures: 1,
    maxFigures: 1,
    variants: ["Llavero personalizado", "Llavero de jugador", "Llavero de personaje"],
    allowsPets: false,
    allowsAccessories: true,
    rule: "Una minifigura por llavero. Dise\u00f1os y piezas sujetos al inventario disponible.",
    isActive: true,
    displayOrder: 64,
    basePrice: 28000,
    code: "LLAV-PER",
  },
  {
    id: "fig-profesiones",
    name: "Profesiones y Oficios",
    kicker: "Minifiguras individuales e imanes",
    category: "Minifiguras",
    detail: "Figura individual o im\u00e1n",
    image: "/catalog-assets/minifiguras/9cc3d850-256f-4a59-b551-85b0a7fe033c.jpg",
    tag: "Colecci\u00f3n",
    group: "Minifiguras",
    occasion: ["Profesiones", "Graduaci\u00f3n"],
    description: "Colecci\u00f3n de minifiguras de Profesiones y Oficios. M\u00e1s de 50 estilos de cabello y 80 rostros disponibles para combinar cabello, rostro, outfit y accesorios.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Figura individual", "Im\u00e1n decorativo"],
    allowsPets: false,
    allowsAccessories: true,
    rule: "Cabello, rostro, outfit y accesorios sujetos a disponibilidad de inventario.",
    isActive: true,
    displayOrder: 65,
    basePrice: 24000,
    code: "FIG-PROFESIONES",
  },
  {
    id: "fig-futbol",
    name: "Futbolistas y Leyendas",
    kicker: "Minifiguras individuales e imanes",
    category: "Minifiguras",
    detail: "Figura individual o im\u00e1n",
    image: "/catalog-assets/minifiguras/eb1d49cf-4e35-42d4-b02e-51b80ca3f7ed.jpg",
    tag: "Colecci\u00f3n",
    group: "Minifiguras",
    occasion: ["Deportes", "Cumplea\u00f1os"],
    description: "Colecci\u00f3n de minifiguras de Futbolistas y Leyendas. M\u00e1s de 50 estilos de cabello y 80 rostros disponibles para combinar cabello, rostro, outfit y accesorios.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Figura individual", "Im\u00e1n decorativo"],
    allowsPets: false,
    allowsAccessories: true,
    rule: "Cabello, rostro, outfit y accesorios sujetos a disponibilidad de inventario.",
    isActive: true,
    displayOrder: 66,
    basePrice: 24000,
    code: "FIG-FUTBOL",
  },
  {
    id: "fig-galaxia",
    name: "Colecci\u00f3n Galaxia",
    kicker: "Minifiguras individuales e imanes",
    category: "Minifiguras",
    detail: "Figura individual o im\u00e1n",
    image: "/catalog-assets/minifiguras/150e20c4-8ea9-4212-94c6-b7e094347ea1.jpg",
    tag: "Colecci\u00f3n",
    group: "Minifiguras",
    occasion: ["Coleccionistas", "Cumplea\u00f1os"],
    description: "Colecci\u00f3n de minifiguras de Colecci\u00f3n Galaxia. M\u00e1s de 50 estilos de cabello y 80 rostros disponibles para combinar cabello, rostro, outfit y accesorios.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Figura individual", "Im\u00e1n decorativo"],
    allowsPets: false,
    allowsAccessories: true,
    rule: "Cabello, rostro, outfit y accesorios sujetos a disponibilidad de inventario.",
    isActive: true,
    displayOrder: 67,
    basePrice: 24000,
    code: "FIG-GALAXIA",
  },
  {
    id: "fig-magia",
    name: "Mundo M\u00e1gico",
    kicker: "Minifiguras individuales e imanes",
    category: "Minifiguras",
    detail: "Figura individual o im\u00e1n",
    image: "/catalog-assets/minifiguras/35bd0e27-9e52-444d-a3bb-f6914b3ac144.jpg",
    tag: "Colecci\u00f3n",
    group: "Minifiguras",
    occasion: ["Coleccionistas", "Cumplea\u00f1os"],
    description: "Colecci\u00f3n de minifiguras de Mundo M\u00e1gico. M\u00e1s de 50 estilos de cabello y 80 rostros disponibles para combinar cabello, rostro, outfit y accesorios.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Figura individual", "Im\u00e1n decorativo"],
    allowsPets: false,
    allowsAccessories: true,
    rule: "Cabello, rostro, outfit y accesorios sujetos a disponibilidad de inventario.",
    isActive: true,
    displayOrder: 68,
    basePrice: 24000,
    code: "FIG-MAGIA",
  },
  {
    id: "fig-heroes",
    name: "H\u00e9roes y Villanos",
    kicker: "Minifiguras individuales e imanes",
    category: "Minifiguras",
    detail: "Figura individual o im\u00e1n",
    image: "/catalog-assets/minifiguras/3b1a6036-5b2b-4a71-be55-7494a0c827cc.jpg",
    tag: "Colecci\u00f3n",
    group: "Minifiguras",
    occasion: ["Coleccionistas", "Cumplea\u00f1os"],
    description: "Colecci\u00f3n de minifiguras de H\u00e9roes y Villanos. M\u00e1s de 50 estilos de cabello y 80 rostros disponibles para combinar cabello, rostro, outfit y accesorios.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Figura individual", "Im\u00e1n decorativo"],
    allowsPets: false,
    allowsAccessories: true,
    rule: "Cabello, rostro, outfit y accesorios sujetos a disponibilidad de inventario.",
    isActive: true,
    displayOrder: 69,
    basePrice: 24000,
    code: "FIG-HEROES",
  },
  {
    id: "fig-aventura",
    name: "Personajes de Aventura",
    kicker: "Minifiguras individuales e imanes",
    category: "Minifiguras",
    detail: "Figura individual o im\u00e1n",
    image: "/catalog-assets/minifiguras/326ff765-15db-4c90-b6e0-8e35b665f560.jpg",
    tag: "Colecci\u00f3n",
    group: "Minifiguras",
    occasion: ["Coleccionistas", "Cumplea\u00f1os"],
    description: "Colecci\u00f3n de minifiguras de Personajes de Aventura. M\u00e1s de 50 estilos de cabello y 80 rostros disponibles para combinar cabello, rostro, outfit y accesorios.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Figura individual", "Im\u00e1n decorativo"],
    allowsPets: false,
    allowsAccessories: true,
    rule: "Cabello, rostro, outfit y accesorios sujetos a disponibilidad de inventario.",
    isActive: true,
    displayOrder: 70,
    basePrice: 24000,
    code: "FIG-AVENTURA",
  },
  {
    id: "fig-animados",
    name: "Favoritos Animados",
    kicker: "Minifiguras individuales e imanes",
    category: "Minifiguras",
    detail: "Figura individual o im\u00e1n",
    image: "/catalog-assets/minifiguras/ab2e970f-ffb1-43fe-b54a-9b5a77b572aa.jpg",
    tag: "Colecci\u00f3n",
    group: "Minifiguras",
    occasion: ["Coleccionistas", "Cumplea\u00f1os"],
    description: "Colecci\u00f3n de minifiguras de Favoritos Animados. M\u00e1s de 50 estilos de cabello y 80 rostros disponibles para combinar cabello, rostro, outfit y accesorios.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Figura individual", "Im\u00e1n decorativo"],
    allowsPets: false,
    allowsAccessories: true,
    rule: "Cabello, rostro, outfit y accesorios sujetos a disponibilidad de inventario.",
    isActive: true,
    displayOrder: 71,
    basePrice: 24000,
    code: "FIG-ANIMADOS",
  },
  {
    id: "fig-clasicos",
    name: "D\u00faos Cl\u00e1sicos",
    kicker: "Minifiguras individuales e imanes",
    category: "Minifiguras",
    detail: "Figura individual o im\u00e1n",
    image: "/catalog-assets/minifiguras/263b7290-6417-4de0-ade4-cec663d73a55.jpg",
    tag: "Colecci\u00f3n",
    group: "Minifiguras",
    occasion: ["Pareja", "Coleccionistas"],
    description: "Colecci\u00f3n de minifiguras de D\u00faos Cl\u00e1sicos. M\u00e1s de 50 estilos de cabello y 80 rostros disponibles para combinar cabello, rostro, outfit y accesorios.",
    minFigures: 1,
    maxFigures: 8,
    variants: ["Figura individual", "Im\u00e1n decorativo"],
    allowsPets: false,
    allowsAccessories: true,
    rule: "Cabello, rostro, outfit y accesorios sujetos a disponibilidad de inventario.",
    isActive: true,
    displayOrder: 72,
    basePrice: 24000,
    code: "FIG-CLASICOS",
  },
  {
    id: "set-hockey",
    name: "Mini Hockey",
    kicker: "Para jugar y exhibir",
    category: "Sets armables",
    detail: "Set interactivo \u00b7 Grupo 1",
    image: "/catalog-assets/sets/50dad80b-49a5-400e-aced-d22c7b4530c7.png",
    tag: "Grupo 1",
    group: "Grupo 1",
    occasion: ["Deportes", "Cumplea\u00f1os"],
    description: "Mini Hockey es un set armable e interactivo para recrear partidos y jugadas memorables con minifiguras personalizadas.",
    minFigures: 1,
    maxFigures: 4,
    variants: ["Grupo 1"],
    allowsPets: true,
    allowsAccessories: true,
    rule: "Grupo 1: 1 minifigura $130.000, 2 minifiguras $158.000.",
    isActive: true,
    displayOrder: 73,
    basePrice: 130000,
    code: "SET-HOCKEY",
  },
];

export const OCCASIONS = [
  'Pareja',
  'Familia',
  'Cumpleaños',
  'Aniversario',
  'Profesiones',
  'Graduación',
  'Amigos',
  'Deportes',
  'Música',
  'Coleccionistas',
  'Vacaciones',
] as const;
